### ISSUE TITLE
pdf pos vuoto

### ISSUE THREAD

**Issue by PaolinoAngeletti** [SoftwareAdvise/segnalazioneBug#3]
azienda : expo
pos:
19.2607.610
23/08/2019
cleinte genrico
6 - Expo Napoli
122 €

rispsota get dati documento
{
  "movimenti": [
    {
      "iva": 0,
      "idAzienda": "exponapoli@magazzinoperfetto.it",
      "tsLastUpdate": "2019-08-23T09:41:01.000Z",
      "posizione": 1,
      "id": "C.2019.2607.2426",
      "tipo": "POS",
      "collo": " ",
      "TS": "2019-08-23T09:41:05.000Z",
      "id_doc_prec": " ",
      "sconto": 0,
      "deposito": "C.2019.2607.1308",
      "seriale": "",
      "stato": 1,
      "qnt4": 1,
      "id_mov_prec": " ",
      "qnt1": 0,
      "qnt3": 0,
      "qnt2": 0,
      "prezzo": 122,
      "ubicazione": " ",
      "idDocumento": "C.2019.2607.2427",
      "articolo": {
        "iva": 0
      },
      "data": "2019-08-23T00:00:00.000Z",
      "scadenza": "0000-00-00"
    }
  ],
  "dati_soggetto": {
    "categoria": "",
    "idAzienda": "malatoperimotori@hotmail.it",
    "tratt_dati": 1,
    "sex": "",
    "pIVA": "",
    "idWC": null,
    "id": "624148030",
    "zona": "",
    "indirizzo": "",
    "provincia": "",
    "iva_def": "",
    "nome": "Generico",
    "id_listino": "",
    "ragioneSociale": "Generico",
    "TS": "2019-01-31T16:38:26.000Z",
    "id_promo": "",
    "stato": 0,
    "localita": "",
    "fascia_eta": "",
    "tsLastUpdate": "2019-01-31T16:28:58.000Z",
    "paese": "",
    "nascita": "0000-00-00",
    "pagam_def": "",
    "sdi": "",
    "codiceFiscale": "",
    "tipo_soggetto": null,
    "codice": "",
    "cognome": null,
    "cap": "",
    "pec": ""
  },
  "dati_azienda": {
    "custom:provincia": "NA",
    "custom:cognome": "Napoli",
    "sub": "8894d5a6-3ca2-4473-bff7-37c2e0af0fbb",
    "custom:ecommerce": "https://exponapoli.magazzinoperfetto.com",
    "email_verified": "true",
    "custom:telefono": "0825.1805630",
    "custom:ragione_sociale": "Expo Napoli",
    "custom:lastAccessApp": "1566551999",
    "custom:codice_fiscale": "06575921215",
    "name": "Expo",
    "custom:idWP": "697",
    "custom:lastAccessCloud": "1565188764",
    "custom:maxDevices": "6",
    "custom:pin": "1316",
    "custom:tipoProfilo": "1",
    "address": "viale Kennedy 54",
    "custom:p_iva": "06575921215",
    "custom:cap": "80125",
    "custom:comune": "Napoli",
    "email": "exponapoli@magazzinoperfetto.it",
    "custom:idAC": "927"
  },
  "contatti_soggetto": {
    "mail": ".@live.it",
    "telefono": "",
    "cellulare": ""
  },
  "documenti_padri": [],
  "dati_destinazione": [],
  "metodo_pagamento": [],
  "dati_documento": {
    "id_fe": null,
    "dataConsegna": "0000-00-00 00:00:00",
    "idAzienda": "exponapoli@magazzinoperfetto.it",
    "idWP": null,
    "tsLastUpdate": "2019-08-23T09:41:01.000Z",
    "idPadre": " ",
    "img_firma": " ",
    "url_documento": null,
    "sendTo": " ",
    "FT": " ",
    "id": "C.2019.2607.2427",
    "tipo": "POS",
    "TS": "2019-08-23T09:41:05.000Z",
    "colli": 0,
    "note": " ",
    "deposito": "C.2019.2607.1308",
    "stato_fe": null,
    "stato": 1,
    "sp_spediz": 0,
    "prezzo": 122,
    "aspetto": " ",
    "nome_file_fe": null,
    "pagamento": "Contanti",
    "check_doc": 0,
    "DDT": " ",
    "xml_file_content": null,
    "sdi_identification": null,
    "fornitore": " ",
    "data": "2019-08-23T00:00:00.000Z",
    "porto": " ",
    "codice": "19.2607.610",
    "creatore": "Admin Admin",
    "iva_sped": 0,
    "causale": "Vendita",
    "trasporto": " ",
    "cliente": "Generico"
  },
  "dati_deposito": {
    "indirizzo": "via roma, 7",
    "provincia": " ",
    "codice": 6,
    "idAzienda": "exponapoli@magazzinoperfetto.it",
    "cap": " ",
    "tsLastUpdate": "2019-08-08T08:49:25.000Z",
    "TS": "2019-08-08T08:49:29.000Z",
    "note": " ",
    "ragione_sociale": "Expo Napoli",
    "paese": " ",
    "stato": 0,
    "idRef": "exponapoli@magazzinoperfetto.it",
    "id": "C.2019.2607.1308",
    "localita": "Avellino"
  }
}

**Comment by andreaferrante79** [comment]
uniforato allo stile fattura acquisti
